# Estrategia de backup para Sensus
backup_strategy:
  name: "Sensus Backup Strategy"
  version: "1.0.0"
  description: "Estrategia completa de backup y recovery para Sensus"

  # Configuración general
  general:
    retention_days: 30
    compression: true
    encryption: true
    encryption_key: "${BACKUP_ENCRYPTION_KEY}"
    storage_provider: "s3"
    storage_region: "us-east-1"
    storage_bucket: "sensus-backups"

  # Tipos de backup
  backup_types:
    # Backup de base de datos
    database:
      enabled: true
      frequency: "daily"
      time: "02:00"
      retention:
        daily: 7
        weekly: 4
        monthly: 12
      databases:
        - name: "sensus_main"
          type: "postgresql"
          host: "postgres:5432"
          database: "sensus"
          username: "${DB_USERNAME}"
          password: "${DB_PASSWORD}"
          tables:
            - "users"
            - "diary_entries"
            - "evaluations"
            - "sessions"
            - "notifications"
        - name: "sensus_analytics"
          type: "postgresql"
          host: "postgres:5432"
          database: "sensus_analytics"
          username: "${DB_USERNAME}"
          password: "${DB_PASSWORD}"

    # Backup de archivos
    files:
      enabled: true
      frequency: "daily"
      time: "03:00"
      retention:
        daily: 7
        weekly: 4
        monthly: 12
      paths:
        - "/app/uploads"
        - "/app/logs"
        - "/app/config"
        - "/app/backups"

    # Backup de configuración
    configuration:
      enabled: true
      frequency: "daily"
      time: "01:00"
      retention:
        daily: 30
        weekly: 12
        monthly: 12
      paths:
        - "/app/config"
        - "/app/.env"
        - "/app/package.json"
        - "/app/package-lock.json"

    # Backup de logs
    logs:
      enabled: true
      frequency: "daily"
      time: "04:00"
      retention:
        daily: 7
        weekly: 4
        monthly: 6
      paths:
        - "/app/logs"
        - "/var/log/nginx"
        - "/var/log/postgresql"

  # Estrategias de backup
  strategies:
    # Backup completo
    full:
      enabled: true
      frequency: "weekly"
      day: "sunday"
      time: "01:00"
      retention: 4
      description: "Backup completo de toda la aplicación"

    # Backup incremental
    incremental:
      enabled: true
      frequency: "daily"
      time: "02:00"
      retention: 7
      description: "Backup incremental diario"

    # Backup diferencial
    differential:
      enabled: true
      frequency: "daily"
      time: "03:00"
      retention: 7
      description: "Backup diferencial diario"

  # Configuración de almacenamiento
  storage:
    # Almacenamiento principal (S3)
    primary:
      provider: "aws_s3"
      bucket: "sensus-backups"
      region: "us-east-1"
      access_key: "${AWS_ACCESS_KEY_ID}"
      secret_key: "${AWS_SECRET_ACCESS_KEY}"
      encryption: "AES256"
      storage_class: "STANDARD_IA"

    # Almacenamiento secundario (Google Cloud)
    secondary:
      provider: "gcp"
      bucket: "sensus-backups-secondary"
      region: "us-central1"
      service_account_key: "${GCP_SERVICE_ACCOUNT_KEY}"
      encryption: "AES256"
      storage_class: "NEARLINE"

    # Almacenamiento local
    local:
      provider: "local"
      path: "/app/backups"
      encryption: true
      compression: true

  # Configuración de notificaciones
  notifications:
    enabled: true
    channels:
      - type: "email"
        recipients:
          - "devops@sensus.app"
          - "admin@sensus.app"
        events:
          - "backup_success"
          - "backup_failure"
          - "backup_restore"
          - "backup_cleanup"

      - type: "slack"
        webhook_url: "${SLACK_WEBHOOK_URL}"
        channel: "#backups"
        events:
          - "backup_success"
          - "backup_failure"
          - "backup_restore"

      - type: "pagerduty"
        service_key: "${PAGERDUTY_SERVICE_KEY}"
        events:
          - "backup_failure"
          - "backup_restore_failure"

  # Configuración de monitoreo
  monitoring:
    enabled: true
    metrics:
      - "backup_duration"
      - "backup_size"
      - "backup_success_rate"
      - "restore_duration"
      - "restore_success_rate"
    
    alerts:
      - name: "backup_failure"
        condition: "backup_status == 'failed'"
        severity: "critical"
        description: "Backup failed"

      - name: "backup_too_large"
        condition: "backup_size > 10GB"
        severity: "warning"
        description: "Backup size is unusually large"

      - name: "backup_too_slow"
        condition: "backup_duration > 2h"
        severity: "warning"
        description: "Backup is taking too long"

      - name: "restore_failure"
        condition: "restore_status == 'failed'"
        severity: "critical"
        description: "Restore failed"

  # Configuración de testing
  testing:
    enabled: true
    frequency: "weekly"
    day: "saturday"
    time: "10:00"
    description: "Test restore from backup"
    retention: 4

  # Configuración de limpieza
  cleanup:
    enabled: true
    frequency: "daily"
    time: "05:00"
    description: "Clean up old backups"
    rules:
      - type: "age"
        value: 30
        unit: "days"
      - type: "count"
        value: 10
        unit: "backups"

  # Configuración de seguridad
  security:
    encryption:
      algorithm: "AES-256-GCM"
      key_rotation: "monthly"
      key_storage: "aws_kms"
    
    access_control:
      - role: "admin"
        permissions: ["read", "write", "delete", "restore"]
      - role: "operator"
        permissions: ["read", "write", "restore"]
      - role: "viewer"
        permissions: ["read"]

    audit_logging:
      enabled: true
      events:
        - "backup_start"
        - "backup_end"
        - "backup_failure"
        - "restore_start"
        - "restore_end"
        - "restore_failure"
        - "backup_delete"
        - "backup_restore"

  # Configuración de disaster recovery
  disaster_recovery:
    enabled: true
    rto: "4h"  # Recovery Time Objective
    rpo: "1h"  # Recovery Point Objective
    
    procedures:
      - name: "database_restore"
        description: "Restore database from backup"
        steps:
          - "Stop application services"
          - "Restore database from latest backup"
          - "Verify database integrity"
          - "Start application services"
          - "Verify application functionality"
      
      - name: "full_system_restore"
        description: "Restore entire system from backup"
        steps:
          - "Provision new infrastructure"
          - "Restore database from backup"
          - "Restore application files"
          - "Restore configuration"
          - "Start application services"
          - "Verify system functionality"
      
      - name: "partial_restore"
        description: "Restore specific components"
        steps:
          - "Identify affected components"
          - "Restore specific components from backup"
          - "Verify component functionality"
          - "Update application configuration"

  # Configuración de compliance
  compliance:
    enabled: true
    standards:
      - "GDPR"
      - "HIPAA"
      - "SOC2"
    
    requirements:
      - "data_encryption_at_rest"
      - "data_encryption_in_transit"
      - "access_logging"
      - "audit_trail"
      - "data_retention"
      - "secure_deletion"
