# Alerting rules for Sensus
groups:
  - name: sensus-backend
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: sensus-backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second for {{ $labels.instance }}"
          runbook_url: "https://docs.sensus.app/runbooks/high-error-rate"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: sensus-backend
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.instance }}"

      # Service down
      - alert: ServiceDown
        expr: up{job="sensus-backend"} == 0
        for: 1m
        labels:
          severity: critical
          service: sensus-backend
        annotations:
          summary: "Sensus backend service is down"
          description: "Backend service has been down for more than 1 minute"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: sensus-backend
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
          service: sensus-backend
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% for {{ $labels.instance }}"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: rate(database_connection_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: sensus-backend
        annotations:
          summary: "Database connection issues"
          description: "Database connection error rate is {{ $value }} errors per second"

      # Authentication failures
      - alert: HighAuthFailureRate
        expr: rate(auth_failures_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          service: sensus-backend
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate is {{ $value }} failures per second"

  - name: sensus-frontend
    rules:
      # Frontend service down
      - alert: FrontendServiceDown
        expr: up{job="sensus-frontend"} == 0
        for: 1m
        labels:
          severity: critical
          service: sensus-frontend
        annotations:
          summary: "Sensus frontend service is down"
          description: "Frontend service has been down for more than 1 minute"

      # High 4xx error rate
      - alert: High4xxErrorRate
        expr: rate(nginx_http_requests_total{status=~"4.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: sensus-frontend
        annotations:
          summary: "High 4xx error rate"
          description: "4xx error rate is {{ $value }} errors per second for {{ $labels.instance }}"

      # High 5xx error rate
      - alert: High5xxErrorRate
        expr: rate(nginx_http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          service: sensus-frontend
        annotations:
          summary: "High 5xx error rate"
          description: "5xx error rate is {{ $value }} errors per second for {{ $labels.instance }}"

  - name: sensus-infrastructure
    rules:
      # Disk space low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: critical
          service: infrastructure
        annotations:
          summary: "Disk space is low"
          description: "Disk space is {{ $value | humanizePercentage }} full on {{ $labels.instance }}"

      # Disk space warning
      - alert: DiskSpaceWarning
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.2
        for: 10m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "Disk space warning"
          description: "Disk space is {{ $value | humanizePercentage }} full on {{ $labels.instance }}"

      # High load average
      - alert: HighLoadAverage
        expr: node_load1 > 4
        for: 10m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "High load average"
          description: "Load average is {{ $value }} for {{ $labels.instance }}"

      # Network interface down
      - alert: NetworkInterfaceDown
        expr: node_network_up == 0
        for: 1m
        labels:
          severity: critical
          service: infrastructure
        annotations:
          summary: "Network interface down"
          description: "Network interface {{ $labels.device }} is down on {{ $labels.instance }}"

  - name: sensus-application
    rules:
      # High user registration rate
      - alert: HighUserRegistrationRate
        expr: rate(user_registrations_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          service: sensus-backend
        annotations:
          summary: "High user registration rate"
          description: "User registration rate is {{ $value }} registrations per second"

      # High diary entry creation rate
      - alert: HighDiaryEntryRate
        expr: rate(diary_entries_created_total[5m]) > 50
        for: 5m
        labels:
          severity: warning
          service: sensus-backend
        annotations:
          summary: "High diary entry creation rate"
          description: "Diary entry creation rate is {{ $value }} entries per second"

      # High evaluation completion rate
      - alert: HighEvaluationRate
        expr: rate(evaluations_completed_total[5m]) > 20
        for: 5m
        labels:
          severity: warning
          service: sensus-backend
        annotations:
          summary: "High evaluation completion rate"
          description: "Evaluation completion rate is {{ $value }} evaluations per second"

      # API rate limiting triggered
      - alert: APIRateLimitTriggered
        expr: rate(api_rate_limit_hits_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: sensus-backend
        annotations:
          summary: "API rate limiting triggered"
          description: "API rate limiting is being triggered at {{ $value }} hits per second"

      # Unusual error patterns
      - alert: UnusualErrorPattern
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05 and rate(http_requests_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          service: sensus-backend
        annotations:
          summary: "Unusual error pattern detected"
          description: "High error rate with high request volume: {{ $value }} errors per second"

  - name: sensus-security
    rules:
      # Brute force attack detection
      - alert: BruteForceAttack
        expr: rate(auth_failures_total{source_ip!=""}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Potential brute force attack detected"
          description: "High authentication failure rate from {{ $labels.source_ip }}: {{ $value }} failures per second"

      # Suspicious activity
      - alert: SuspiciousActivity
        expr: rate(http_requests_total{status=~"4.."}[5m]) > 0.2
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Suspicious activity detected"
          description: "High 4xx error rate: {{ $value }} errors per second"

      # Unusual request patterns
      - alert: UnusualRequestPattern
        expr: rate(http_requests_total[5m]) > 100
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Unusual request pattern detected"
          description: "High request rate: {{ $value }} requests per second"

  - name: sensus-business
    rules:
      # Low user engagement
      - alert: LowUserEngagement
        expr: rate(diary_entries_created_total[1h]) < 0.1
        for: 1h
        labels:
          severity: warning
          service: business
        annotations:
          summary: "Low user engagement"
          description: "Diary entry creation rate is {{ $value }} entries per second"

      # High user churn
      - alert: HighUserChurn
        expr: rate(user_deletions_total[1h]) > 0.01
        for: 1h
        labels:
          severity: warning
          service: business
        annotations:
          summary: "High user churn"
          description: "User deletion rate is {{ $value }} deletions per second"

      # Low evaluation completion
      - alert: LowEvaluationCompletion
        expr: rate(evaluations_completed_total[1h]) < 0.05
        for: 1h
        labels:
          severity: warning
          service: business
        annotations:
          summary: "Low evaluation completion rate"
          description: "Evaluation completion rate is {{ $value }} completions per second"
