name: Dependabot Security Updates

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 6 * * *' # Daily at 6 AM

jobs:
  dependabot:
    name: Dependabot Security Updates
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run npm audit
        run: npm audit --audit-level moderate
        
      - name: Run npm audit fix
        run: npm audit fix --force
        continue-on-error: true
        
      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: audit-results
          path: npm-audit.json
